spring:
  application:
    name: pet-api
  datasource:
    password: postgres
    username: postgres
    name: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres

  flyway:
    password: postgres
    user: postgres
  jpa:
    show-sql: false
  data:
    redis:
      username: ${REDIS_USERNAME:redis}
      password: ${REDIS_PASSWORD:redis}
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
springdoc:
  swagger-ui:
    path: /
    url: /openapi.yml
