logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.opentelemetry: DEBUG
    io.opentelemetry.exporter.otlp: DEBUG
    io.micrometer.tracing: DEBUG
    io.prometheus.metrics: DEBUG