spring:
  application:
    name: pet-api
  datasource:
    password: postgres
    username: postgres
    name: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres

  flyway:
    password: postgres
    user: postgres
  jpa:
    show-sql: true
  data:
    redis:
      username: redis
      password: redis
      host: localhost
      port: 6379