events {
    worker_connections 1024;
}

http {

    upstream pet_backend {
        server pet-service:8083;
    }

    upstream metrics_backend {
        server pet-service:9091;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://pet_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /actuator {
            proxy_pass http://metrics_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

#         location / {
#             root /var/www/html/site;
#             try_files $uri $uri/ /index.html =404;
#             include /etc/nginx/mime.types;
#         }
    }
}
